version: '3.9'

services:
  app:
    build: .
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - APP_SECRETE=${APP_SECRETE}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - ${PORT}:8080
    depends_on:
      - redis
      - database
    command: sh -c 'yarn build && yarn setup && yarn start'
    volumes:
      - .:/opt/app
    
  
  
  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379

  database:
    image: mariadb:10.7.1
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes!
